# This is the default analysis_options.yaml for all packages and examples
# If a package needs specific rules, create the analysis_options.yaml on it
# include this file, like:
#
# include: ../../analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'analysis_options.yaml'
    - '**/*.g.dart'

linter:
  rules:
    # TODO: Change this rule to true and fix the code
    prefer_const_constructors: false
    prefer_final_in_for_each: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
