name: school
description: Aplicativo de gestão de notas e presenças escolares

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.1.0
  cloud_firestore: ^3.1.0  
  firebase_core: ^1.8.0
  flux_validator_dart: ^2.0.0
  cnpj_cpf_formatter_nullsafety: ^1.1.1
  validators2: ^3.0.0
  firebase_auth: ^3.2.0
  flutter_modular: ^4.2.0
  multi_select_flutter: ^4.0.0
  rounded_expansion_tile: ^0.0.13
  flutter_slidable: ^1.1.0
  dropdown_search: ^2.0.1
  multiselect: ^0.0.4
  mask_text_input_formatter: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  datetime_picker_formfield: ^2.0.0
  pdf: ^3.6.5
  open_file: ^3.2.1
  path_provider: ^2.0.8
  intl: ^0.17.0
  
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^1.10.1
  flutter_launcher_icons: ^0.9.2
  asuka: ^2.0.0-nullsafety.2
  flutter_native_splash: ^1.3.1

flutter_native_splash:
  color: "5f9bbb"
  android: true
  ios: true




flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/app_icon.png"
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/banners/


  fonts:
    - family: Arial
      fonts:
        - asset: assets/arial.ttf
    - family: Courier
      fonts:
        - asset: assets/courier.ttf
          
 

